#配置Tomcat
server:
  port: 8088
  tomcat.max-threads: 50
  tomcat.uri-encoding: UTF-8


#配置eureka   当前关闭注册eureka
eureka:
  client:
#    service-url: "http://localhost:1111/eureka"
    register-with-eureka: false
    fetch-registry: false
#配置连接数据库
spring:
  application:
    name: study
  datasource:
    url: jdbc:mysql://192.168.0.8:3306/test_mo?characterEncoding=utf8
    username: root
    password: mysql@pwd123
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:WEB-INF/templates/
    suffix: .html
    encoding: UTF-8
    enabled: true
    cache: false
    servlet:
      content-type: text/html
mybatis:
  type-aliases-package: com.myz.study.domain
  mapper-locations: classpath:mapper/*.xml
